In [1]:
import torch
import time
import pandas as pd
import numpy as np
import math
import matplotlib.pyplot as plt

# Intro. to Tensors

### Creating Tensors

Pytorch are created using `torch.Tensor()`

Scalor

In [2]:
# scalor 
scalor = torch.tensor(7)
scalor

tensor(7)

In [3]:
print("Dimension of a scalor:", scalor.ndim)
print("Shapes of a scalor:", scalor.shape)

Dimension of a scalor: 0
Shapes of a scalor: torch.Size([])


Vector

In [4]:
# vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [5]:
print("Dimension of a vector:", vector.ndim)
print("Shapes of a vector:", vector.shape)

Dimension of a vector: 1
Shapes of a vector: torch.Size([2])


Matrix

In [6]:
MATRIX = torch.tensor([
    [7, 8],
    [9, 10]
])

MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [7]:
print("Dimension of a matrix:", MATRIX.ndim)
print("Shapes of a matrix:", MATRIX.shape)

Dimension of a matrix: 2
Shapes of a matrix: torch.Size([2, 2])


### Random Tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is that the ystart with tensors full of random numbers and then adjust those random numbers to better represent data.

In [8]:
#  Create a random tensor of shape (3, 4)

random_tensor = torch.rand(3, 4) # It will create a tensor with value between 0 and 1
random_tensor

tensor([[0.7744, 0.2976, 0.6823, 0.4485],
        [0.9489, 0.0450, 0.9798, 0.1564],
        [0.5571, 0.4756, 0.0273, 0.2755]])

In [9]:
# Create a tensor which is similar shape to an image tensor

rand_image_tensor = torch.rand(size=(224, 224, 3)) # Which represented Height Width and Color Channels respectively
rand_image_tensor.shape, rand_image_tensor.ndim

(torch.Size([224, 224, 3]), 3)

## Zeros and Ones

In [10]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [11]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

### Creating a range of tensors and tensor-like

In [12]:
# Use torch.arange()
one_to_ten = torch.arange(start = 0, end = 10, step = 1)
one_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
# Creating tensor-like
like = torch.zeros_like(one_to_ten)
like

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

**Note:** Tensor datatype is one of the 3 big issues with PyTorch errors yot will run into with Pytorch
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [14]:
float_32_tensors = torch.tensor([3.0, 6.0, 9.0],
                                dtype = None, # What datatype of the tensor
                                device = None, # Default is "CPU", in MAC we can use "META" to obtain accessibality of M2 GPU
                                requires_grad = False) # Tracking  gradients with this tensors operatopn or not

float_32_tensors.dtype

torch.float32

In [15]:
float_16_tensors = float_32_tensors.type(torch.float16)
float_16_tensors.dtype

torch.float16

### Getting informations from tensors

1. Tensors not right datatype - to get data type from a tensor we can use `tensor.dtype`
2. Tensors not right shape - to get tensor shape we can use `tensor.shape`
3. Tensors not on the right device - to get which device we are using we can use `tensor.device`

In [16]:
float_32_tensors.dtype, float_32_tensors.shape, float_32_tensors.device

(torch.float32, torch.Size([3]), device(type='meta'))

### Tensor operations (Manipulation Tensors)

Tensors operation include:
* Addition `torch.add()`
* Subtraction `torch.sub`
* Mutiplication (element-wise) `torch.mul`
* Dvision `torch.div`
* Matrix Mutiplication

In [17]:
# Create a tensor
tensor = torch.tensor([1, 2, 3])
print(f"Addition of tensor: {tensor + 10}")
print(f"Subtraction of tensor: {tensor - 10}")
print(f"Mutiplication of tensor: {tensor * 10}")

Addition of tensor: tensor([11, 12, 13])
Subtraction of tensor: tensor([-9, -8, -7])
Mutiplication of tensor: tensor([10, 20, 30])


In [18]:
# Try our PyTorch in built functions
torch.add(tensor, 10), torch.sub(tensor, 10), torch.mul(tensor, 10), torch.div(tensor, 10)

(tensor([11, 12, 13]),
 tensor([-9, -8, -7]),
 tensor([10, 20, 30]),
 tensor([0.1000, 0.2000, 0.3000]))

### Matrix mutiplication

There are two main ways of performing mutiplication in neural network and deep learning

1. Element-wise
2. Matrix multiplication **(dot product)** `torch.matmul()`

The are two rules that performing matrix mutiplication need to satisfy:
1. The **inner dimension** must match:
* `(3, 2) @ (3, 2)` will not work
* `(3, 2) @ (2, 3)` will work
2. The resulting matrix has the shape of the **outer dimensions**:
* `(2, 3) @ (3, 2)` -> `(2, 2)` 

In [19]:
A = torch.tensor([
    [1, 2],
    [3, 4]
])

B = torch.tensor([
    [1, 2],
    [3, 4]
])

torch.matmul(A, B)

tensor([[ 7, 10],
        [15, 22]])

### One of the most common errors in deep learning: shape errors

`torch.mm` is same as `torch.matmul`

In [20]:
# Shape for matrix mutiplication
tensorA = torch.Tensor([
    [1, 2],
    [3, 4],
    [5, 6]
])

tensorB = torch.Tensor([
    [7, 10],
    [8, 11],
    [9, 12]
])

# torch.mm(tensorA, tensorB) # Here will cause shape error


**RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)**

#####  How can we adjust the shape of this? We can use **transpose**

* What we will do is use `tensor.T` which means transpose.

In [21]:
tensorB.T, tensorB.shape, tensorB.T.shape

(tensor([[ 7.,  8.,  9.],
         [10., 11., 12.]]),
 torch.Size([3, 2]),
 torch.Size([2, 3]))

In [22]:
tensorA = tensorA.type(dtype = torch.float32)
tensorB_transpose = tensorB.T
tensorB_transpose.dtype, tensorA.dtype
torch.mm(tensorA, tensorB_transpose)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

### Findind the min, max, mean, sum (tensor aggregation)

In [23]:
x = torch.arange(start=0, end=100, step=10)
x = x.type(dtype=torch.float32) # Cast it to float32 dtype. Otherwise, we can not caculate the mean of it.

In [24]:
torch.min(x), torch.max(x), torch.sum(x), torch.mean(x)

(tensor(0.), tensor(90.), tensor(450.), tensor(45.))

### Finding positional min and max
* Using `.argmin()`
* Using `.argmax()`

In [25]:
X = torch.rand(5)*100
X = X.type(dtype=torch.float32)
X

tensor([97.7075, 95.7101, 75.7454, 54.8936, 17.7360])

In [26]:
index_min = X.argmin()
index_max = X.argmax()

print("Min index:", index_min, " The value is:", X[index_min])
print("Max index:", index_max, " The value is:", X[index_max])

Min index: tensor(4)  The value is: tensor(17.7360)
Max index: tensor(0)  The value is: tensor(97.7075)


### Reshpaing, stacking, squeezing and unsqueeze tensor

* Reshaping - reshape an input tensor to a defined shape -> `.reshape()`
* View - Retern a view of an input tensor of certain shape `.view()`
* Stacking - Combine multiple tensor together `.stack()`
* Squeeze - Remove a **1** dimension from a tensor `.squeeze()`
* Unsqueeze - Add a **1** dimensional to a tensor `.unsqueeze()`
* Permute - Return a view of the input with dimensions permuted in a certain way `torch.permute()`

In [27]:
# Let's create a tensor
X = torch.arange(1., 11.)
X, X.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), torch.Size([10]))

In [28]:
# Add an extra dimension
X_reshape = X.reshape(5, 2)
X_reshape

tensor([[ 1.,  2.],
        [ 3.,  4.],
        [ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])

In [29]:
# Change the view
z = X.view(1, 10)

Changing z will change X ( they share same memory) !!

In [30]:
# Stack tensor on top each other 
x_stack = torch.stack([X, X, X, X], dim=0)
x_stack

tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])

### PyTorch tensors and NumPy

Numpy is a popular scientific Python numerical computing library.

Because of this PyTorch has functionally to interact with it.
* Data in NumPy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`
* PyTorch tensor -> Numpy -> `torch.Tensor.numpy()`

In [31]:
array = np.arange(1., 8.)
tensor = torch.from_numpy(array)

tensor

tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64)

`🤖Reminder: Convert numpt to tensor, data type will be float64. Is different with torch.tensor original data tpye, which is float32. `

In [32]:
# Tensor to NumPy array
tensor = torch.ones(7).type(torch.float64)
print(tensor, tensor.dtype)

array = torch.Tensor.numpy(tensor)
print(array, array.dtype)

tensor([1., 1., 1., 1., 1., 1., 1.], dtype=torch.float64) torch.float64
[1. 1. 1. 1. 1. 1. 1.] float64


### Reproducbility (trying to take random out of random)

In short how a neural network learns:

`🍋 start with random numbers -> tensor operations -> update random numbers to try and make them better representation of the data -> again and again`

* In here we use `torch.manual_seed(RANDOM_SEED)` unlike tensorflow we used `tf.random.set_seed(RANDOM_SEED)`

In [36]:
# To fix the result we need to set seed 
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
torch.rand(3, 3)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009],
        [0.2566, 0.7936, 0.9408]])

#### For MAC user we can use mps instead as our GPU

In [49]:
#check for gpu
if torch.backends.mps.is_available():
   mps_device = torch.device("mps")
   x = torch.ones(1, device=mps_device)
   print (x)
else:
   print ("MPS device not found.")

tensor([1.], device='mps:0')
